server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/laptify_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:your_secret_key_here}
    issuer: ${JWT_ISSUER:Laptify}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000} # 1 hour
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:86400000} # 24 hours

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:your_cloud_name}
  api-key: ${CLOUDINARY_API_KEY:your_api_key}
  api-secret: ${CLOUDINARY_API_SECRET:your_api_secret}
